2024-08-14 13:23:06,188 - main - ERROR - Error without request: POST http://127.0.0.1:8000/user/login
Traceback (most recent call last):
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/anyio/streams/memory.py", line 105, in receive
    return self.receive_nowait()
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/anyio/streams/memory.py", line 100, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/anyio/streams/memory.py", line 118, in receive
    return receiver.item
AttributeError: 'MemoryObjectItemReceiver' object has no attribute 'item'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/starlette/middleware/base.py", line 159, in call_next
    message = await recv_stream.receive()
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/anyio/streams/memory.py", line 120, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/main.py", line 35, in log_exceptions
    response = await call_next(request)
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/starlette/middleware/base.py", line 165, in call_next
    raise app_exc
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/starlette/middleware/base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/fastapi/routing.py", line 193, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/starlette/concurrency.py", line 42, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/routes.py", line 24, in login
    return UserController(params).login()
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/src/controllers/UserController.py", line 29, in login
    'access_token': UserUtil.generate_token({'name': user["name"], 'email': user["email"], 'plan': plan['title']}),
TypeError: 'NoneType' object is not subscriptable
2024-08-14 13:23:37,146 - main - ERROR - Error without request: POST http://127.0.0.1:8000/user/login
Traceback (most recent call last):
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/anyio/streams/memory.py", line 105, in receive
    return self.receive_nowait()
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/anyio/streams/memory.py", line 100, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/anyio/streams/memory.py", line 118, in receive
    return receiver.item
AttributeError: 'MemoryObjectItemReceiver' object has no attribute 'item'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/starlette/middleware/base.py", line 159, in call_next
    message = await recv_stream.receive()
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/anyio/streams/memory.py", line 120, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/main.py", line 35, in log_exceptions
    response = await call_next(request)
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/starlette/middleware/base.py", line 165, in call_next
    raise app_exc
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/starlette/middleware/base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/fastapi/routing.py", line 193, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/starlette/concurrency.py", line 42, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/routes.py", line 24, in login
    return UserController(params).login()
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/src/controllers/UserController.py", line 17, in login
    plan = self.mysql.get_user_plan((user['id'], ))
TypeError: list indices must be integers or slices, not str
2024-08-19 17:59:37,042 - main - ERROR - Error without request: GET http://127.0.0.1:8000/transcribes
Traceback (most recent call last):
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/anyio/streams/memory.py", line 105, in receive
    return self.receive_nowait()
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/anyio/streams/memory.py", line 100, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/anyio/streams/memory.py", line 118, in receive
    return receiver.item
AttributeError: 'MemoryObjectItemReceiver' object has no attribute 'item'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/starlette/middleware/base.py", line 159, in call_next
    message = await recv_stream.receive()
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/anyio/streams/memory.py", line 120, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/main.py", line 35, in log_exceptions
    response = await call_next(request)
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/starlette/middleware/base.py", line 165, in call_next
    raise app_exc
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/starlette/middleware/base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/fastapi/routing.py", line 193, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/starlette/concurrency.py", line 42, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/routes.py", line 23, in transcribes
    return UserController(user).get_transcribes()
TypeError: UserController.__init__() missing 1 required positional argument: 'user'
2024-08-19 17:59:51,305 - main - ERROR - Error without request: GET http://127.0.0.1:8000/transcribes
Traceback (most recent call last):
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/anyio/streams/memory.py", line 105, in receive
    return self.receive_nowait()
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/anyio/streams/memory.py", line 100, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/anyio/streams/memory.py", line 118, in receive
    return receiver.item
AttributeError: 'MemoryObjectItemReceiver' object has no attribute 'item'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/starlette/middleware/base.py", line 159, in call_next
    message = await recv_stream.receive()
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/anyio/streams/memory.py", line 120, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/main.py", line 35, in log_exceptions
    response = await call_next(request)
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/starlette/middleware/base.py", line 165, in call_next
    raise app_exc
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/starlette/middleware/base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/fastapi/routing.py", line 193, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/starlette/concurrency.py", line 42, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "/home/nubbi0174/my-projects/video-trasncribe/video-transcribe-backend/routes.py", line 23, in transcribes
    return UserController(user).get_transcribes()
TypeError: UserController.__init__() missing 1 required positional argument: 'user'
